// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMDHoc1kTDEIBBj_QbvnxqrqJMPCYi-C0',
    appId: '1:540623255080:web:5c914d7c97968df995271d',
    messagingSenderId: '540623255080',
    projectId: 'mytodo-6d06d',
    authDomain: 'mytodo-6d06d.firebaseapp.com',
    storageBucket: 'mytodo-6d06d.appspot.com',
    measurementId: 'G-KJH3HDMQX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr8tcop6cVynSEuyQZJ9cAd6xwWH_CQfY',
    appId: '1:540623255080:android:e6a9e86fda06056495271d',
    messagingSenderId: '540623255080',
    projectId: 'mytodo-6d06d',
    storageBucket: 'mytodo-6d06d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYVFwLDsRcRavyCs-mwOYXdPVbDvtH7BM',
    appId: '1:540623255080:ios:7ca9e8963a1615b595271d',
    messagingSenderId: '540623255080',
    projectId: 'mytodo-6d06d',
    storageBucket: 'mytodo-6d06d.appspot.com',
    iosClientId: '540623255080-9es5blriddspil38rff3o79ak5qvrf9p.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseNoteTaker',
  );
}
